var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...all]/route.js")
R.c("server/chunks/node_modules_d641e16e._.js")
R.c("server/chunks/[root-of-the-server]__45fcc836._.js")
R.c("server/chunks/node_modules_next_dist_a5cd6597._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_better-auth_dist_328d7a0e._.js")
R.c("server/chunks/node_modules_zod_4055c551._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_1e40532a._.js")
R.c("server/chunks/node_modules_@better-auth_core_dist_d3a2a7ce._.js")
R.c("server/chunks/node_modules_kysely_dist_esm_8956dd0c._.js")
R.c("server/chunks/node_modules_@neondatabase_serverless_index_mjs_2c73916b._.js")
R.c("server/chunks/node_modules_ws_570778bb._.js")
R.c("server/chunks/node_modules_91e6dbce._.js")
R.m("[project]/.next-internal/server/app/api/auth/[...all]/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/auth/[...all]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/auth/[...all]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
