/**
 * NodeType enum — replaces the Prisma-generated enum now that we're fully offline.
 * Only file-processing nodes are kept; AI/credential/messaging nodes are removed.
 */
export enum NodeType {
  INITIAL = "INITIAL",
  MANUAL_TRIGGER = "MANUAL_TRIGGER",
  UPLOAD_FILE = "UPLOAD_FILE",
  CSV_PARSE = "CSV_PARSE",
  CSV_FILTER = "CSV_FILTER",
  CSV_SORT = "CSV_SORT",
  CSV_JOIN = "CSV_JOIN",
  CSV_AGGREGATE = "CSV_AGGREGATE",
  CSV_DEDUPLICATE = "CSV_DEDUPLICATE",
  CSV_COMPARE = "CSV_COMPARE",
  CSV_CONSECUTIVE_SEQUENCE_ANALYZER = "CSV_CONSECUTIVE_SEQUENCE_ANALYZER",
  CSV_TRANSFORM = "CSV_TRANSFORM",
  CSV_COLUMN_TRANSFORM = "CSV_COLUMN_TRANSFORM",
  CSV_RESTRUCTURE = "CSV_RESTRUCTURE",
  CSV_GENERATE = "CSV_GENERATE",
  PDF_EXTRACT_TEXT = "PDF_EXTRACT_TEXT",
  PDF_EXTRACT_TABLES = "PDF_EXTRACT_TABLES",
  PDF_SPLIT = "PDF_SPLIT",
  PDF_MERGE = "PDF_MERGE",
  PDF_FILL_FORM = "PDF_FILL_FORM",
  PDF_GENERATE = "PDF_GENERATE",
  PDF_SIGN = "PDF_SIGN",
  FILE_EXPORT = "FILE_EXPORT",
}
