var R=require("./chunks/[turbopack]_runtime.js")("server/instrumentation.js")
R.c("server/chunks/[root-of-the-server]__b24e5763._.js")
R.c("server/chunks/node_modules_@sentry_core_build_cjs_7ad0a532._.js")
R.c("server/chunks/node_modules_@sentry_nextjs_build_cjs_60730947._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_e96249e4._.js")
R.c("server/chunks/node_modules_3f9f62c0._.js")
R.c("server/chunks/node_modules_b2c94ed6._.js")
R.c("server/chunks/node_modules_eaeaae39._.js")
R.c("server/chunks/94679_@sentry_node-core_build_cjs_06f894a8._.js")
R.c("server/chunks/node_modules_01ac51b7._.js")
R.c("server/chunks/node_modules_@sentry_bc9d860f._.js")
R.c("server/chunks/node_modules_@apm-js-collab_code-transformer_pkg_orchestrion_js_73ebd7cd.js")
R.c("server/chunks/node_modules_@apm-js-collab_code-transformer_index_87720b9d.js")
R.c("server/chunks/node_modules_@sentry_node_build_cjs_9410b350._.js")
R.c("server/chunks/node_modules_085a8feb._.js")
R.c("server/chunks/[root-of-the-server]__78cf7c50._.js")
R.m("[project]/src/instrumentation.ts [instrumentation] (ecmascript)")
module.exports=R.m("[project]/src/instrumentation.ts [instrumentation] (ecmascript)").exports
