-- AlterEnum
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'CSV_SORT';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'CSV_DEDUPLICATE';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'CSV_COLUMN_STATS';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'CSV_COMPARE';
