-- AlterEnum
ALTER TYPE "CredentialType" ADD VALUE 'DISCORD_WEBHOOK';
ALTER TYPE "CredentialType" ADD VALUE 'SLACK_WEBHOOK';
ALTER TYPE "CredentialType" ADD VALUE 'TELEGRAM_BOT';
ALTER TYPE "CredentialType" ADD VALUE 'EMAIL_SMTP';

-- AlterEnum
ALTER TYPE "NodeType" ADD VALUE 'EMAIL_SMTP';
